IF(GDCM_FOUND)
  # Nothing here for now
   # Load the compiler settings used for GDCM
  IF(GDCM_BUILD_SETTINGS_FILE)
    INCLUDE(${CMAKE_ROOT}/Modules/CMakeImportBuildSettings.cmake)
    CMAKE_IMPORT_BUILD_SETTINGS(${GDCM_BUILD_SETTINGS_FILE})
  ENDIF(GDCM_BUILD_SETTINGS_FILE)

  # Add compiler flags needed to use VTK.
  #  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${VTK_REQUIRED_C_FLAGS}")
  #  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${VTK_REQUIRED_CXX_FLAGS}")
  #  SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${VTK_REQUIRED_EXE_LINKER_FLAGS}")
  #  SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${VTK_REQUIRED_SHARED_LINKER_FLAGS}")
  #  SET(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_MODULE_LINKER_FLAGS} ${VTK_REQUIRED_MODULE_LINKER_FLAGS}")

  # Add include directories needed to use GDCM
  INCLUDE_DIRECTORIES(${GDCM_INCLUDE_DIRS})

  # Add link directories needed to use GDCM
  LINK_DIRECTORIES(${GDCM_LIBRARY_DIRS})

ENDIF(GDCM_FOUND)
